### ISSUE TITLE
Provide a way to 'anonymize' line numbers when building a Snippet

### ISSUE THREAD

**Issue by phansch** [rust-lang/annotate-snippets-rs#2]
In the rust test suite there's the option to replace line numbers in the diagnostics output with letters, so that changes in the output produce less noisy diffs.

With that flag enabled, the following

```
error: cannot concatenate a byte string literal
  --> $DIR/concat.rs:2:13
   |
 2 |     concat!(b'f');
   |             ^^^^
```

is turned into

```
error: cannot concatenate a byte string literal
  --> $DIR/concat.rs:2:13
   |
LL |     concat!(b'f');
   |             ^^^^
```

Any line number is replaced by `LL`, no matter the digits of that number.

AFAICT, rustc would currently have to implement its own `Snippet -> DisplayList` conversion, which would duplicate a lot of the conversion code just to anonymize the line numbers.

I think this would be nice to have inside `annotate-snippets` too, maybe as an option when constructing a Snippet? I believe other users of this library could also benefit from this option.

**Comment by zbraniecki** [comment]
What happens if there are multiple lines? Are all of them `LL` or is it `LM` and so on? If it's all LL then it should be trivial to implement.

First, you need to adjust the `lineno_width` algo to recognize this option and hardcode it to `2` here - https://github.com/rust-lang/annotate-snippets-rs/blob/master/src/formatter/mod.rs#L74

Second, you need to branch in `format_line` to use `LL` here: https://github.com/rust-lang/annotate-snippets-rs/blob/master/src/formatter/mod.rs#L288

Done! :)

**Comment by Manishearth** [comment]
All of them are LL.

The idea is that the line number shows up on the top with the filename and nowhere else
