### ISSUE TITLE
Origin line number is not correct when using a slice with `fold: true`

### ISSUE THREAD

**Issue by lucacasonato** [rust-lang/annotate-snippets-rs#52]
Here is a test case demonstrating the issue:

```rs
#[test]
fn test_origin_line_numbers_with_fold() {
    let snippets = Snippet {
        title: Some(snippet::Annotation {
            id: None,
            label: Some("oops"),
            annotation_type: snippet::AnnotationType::Error,
        }),
        footer: vec![],
        slices: vec![snippet::Slice {
            source: "First line\r\n\r\n\r\nSecond oops line",
            line_start: 1,
            origin: Some("<current file>"),
            annotations: vec![
                snippet::SourceAnnotation {
                    range: (23, 27),
                    label: "oops",
                    annotation_type: snippet::AnnotationType::Error,
                },
                snippet::SourceAnnotation {
                    range: (0, 5),
                    label: "First",
                    annotation_type: snippet::AnnotationType::Info,
                },
            ],
            fold: true,
        }],
        opt: Default::default(),
    };
    let expected = r#"error: oops
 --> <current file>:4:8
  |
1 | First line
  | ----- info: First
...
4 | Second oops line
  |        ^^^^ oops
  |"#;

    assert_eq!(DisplayList::from(snippets).to_string(), expected);
}
```

`--> <current file>:2:8` is printed instead of `--> <current file>:4:8`.

**Comment by cellog** [comment]
just ran into this bug. There is a working pull request that is a year and a half old. is annotate-snippets unmaintained?

**Comment by zbraniecki** [comment]
It's not unmaintained, but I haven't had time to work on it lately

**Comment by ironcev** [comment]
Hi @zbraniecki, thanks for keep maintaining the _annotate-snippets_! The [Sway programming language](https://github.com/FuelLabs/sway/) uses _annotate-snippets_ for printing its compiler output. We are just switching from short single-slice Snippets where we didn't fold the lines, to larger multi-slice Snippets where we fold the lines and where we see this bug.

The bug is fixed, but not provided in any release. Can you please publish a new patch release with this fix? It would help us a lot.

Thanks in advance!
